import type { FundingProduct } from '../../types/fundingProduct';

export const INITIAL_FUNDING_PRODUCTS: FundingProduct[] = [
  {
    id: 'fund_prod_fundbox_loc',
    name: 'Revolving Business Line of Credit',
    provider: 'Fundbox',
    category: 'Business Line of Credit',
    description: 'Flexible revolving credit line to bridge cash flow gaps, finance invoices, and cover operational payroll.',
    websiteUrl: 'https://fundbox.com',
    affiliateUrl: 'https://fundbox.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: '600+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 150000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Inventory'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_ondeck_term',
    name: 'Fixed-Rate Small Business Term Loan',
    provider: 'OnDeck',
    category: 'Term Loan',
    description: 'Short-to-medium term business loan with fixed repayment schedules for inventory expansion and bulk asset acquisitions.',
    websiteUrl: 'https://ondeck.com',
    affiliateUrl: 'https://ondeck.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 12,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '625+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 250000,
    fundingPurposes: ['Expansion', 'Inventory', 'Working Capital'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_triton_equipment',
    name: 'Commercial Equipment Lease & Financing',
    provider: 'Triton Capital',
    category: 'Equipment Financing',
    description: 'Equipment-backed loans and lease agreements allowing the purchased machinery or hardware to serve as primary security.',
    websiteUrl: 'https://tritoncapital.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 350000,
    fundingPurposes: ['Equipment', 'Vehicle'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_lendio_sba',
    name: 'SBA 7(a) & Express Loan Marketplace',
    provider: 'Lendio',
    category: 'SBA-related Financing',
    description: 'Government-backed low-rate financing designed for established businesses seeking long amortization periods and large capital.',
    websiteUrl: 'https://lendio.com',
    affiliateUrl: 'https://lendio.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '680+',
    businessCreditRequired: 'yes',
    minFundingAmount: 30000,
    maxFundingAmount: 5000000,
    fundingPurposes: ['Expansion', 'Debt Refinancing', 'Business Acquisition'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_national_funding',
    name: 'Working Capital Short-Term Advance',
    provider: 'National Funding',
    category: 'Working Capital',
    description: 'Fast evaluation working capital suited for newer operations requiring quick bridge liquidity without lengthy underwriting.',
    websiteUrl: 'https://nationalfunding.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 100000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Marketing'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_capital_card',
    name: 'Business Credit Card for LLCs',
    provider: 'Capital on Tap',
    category: 'Business Credit Card',
    description: 'Dedicated corporate credit card with flexible limits up to $50,000, cash back terms, and commercial credit reporting.',
    websiteUrl: 'https://capitalontap.com',
    affiliateUrl: 'https://capitalontap.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: '650+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 1000,
    maxFundingAmount: 50000,
    fundingPurposes: ['Everyday Expenses', 'Working Capital', 'Marketing'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
];
