import type { FundingProduct } from '../../types/fundingProduct';

export const INITIAL_FUNDING_PRODUCTS: FundingProduct[] = [
  {
    id: 'fund_prod_fundbox_loc',
    name: 'Revolving Business Line of Credit',
    provider: 'Fundbox',
    category: 'Business Line of Credit',
    description: 'Flexible revolving credit line to bridge cash flow gaps, finance invoices, and cover operational payroll.',
    websiteUrl: 'https://fundbox.com',
    affiliateUrl: 'https://fundbox.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: '600+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 150000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Inventory'],
    repaymentType: 'Revolving',
    rateTermsInfo: 'Draw fee from 4.66% per 12-week or 8.99% per 24-week draw',
    typicalTermRange: 'Revolving (12 or 24-week draws)',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_bluevine_loc',
    name: 'Fast-Draw Business Line of Credit',
    provider: 'Bluevine',
    category: 'Business Line of Credit',
    description: 'On-demand revolving credit access with 24-hour approval decisions, transparent simple-interest rates, and weekly or monthly repayment flexibility.',
    websiteUrl: 'https://www.bluevine.com',
    affiliateUrl: 'https://www.bluevine.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '625+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 6000,
    maxFundingAmount: 250000,
    fundingPurposes: ['Working Capital', 'Cash Flow Buffer', 'Inventory', 'Payroll'],
    repaymentType: 'Revolving',
    rateTermsInfo: 'Rates from 6.2% simple interest (subject to underwriting)',
    typicalTermRange: 'Revolving (6 or 12 months)',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_ondeck_term',
    name: 'Fixed-Rate Small Business Term Loan',
    provider: 'OnDeck',
    category: 'Term Loan',
    description: 'Short-to-medium term business loan with fixed repayment schedules for inventory expansion and bulk asset acquisitions.',
    websiteUrl: 'https://ondeck.com',
    affiliateUrl: 'https://ondeck.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 12,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '625+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 250000,
    fundingPurposes: ['Expansion', 'Inventory', 'Working Capital'],
    repaymentType: 'Medium Term',
    rateTermsInfo: 'Starting at 11.8% simple interest or weighted factor rate',
    typicalTermRange: '12–24 months',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_funding_circle',
    name: 'Commercial Expansion Term Loan',
    provider: 'Funding Circle',
    category: 'Term Loan',
    description: 'Fixed-rate term financing with 6-month to 7-year terms and zero prepayment penalties, ideal for established business growth and expansion.',
    websiteUrl: 'https://www.fundingcircle.com',
    affiliateUrl: 'https://www.fundingcircle.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$150,000',
    minPersonalCredit: '660+',
    businessCreditRequired: 'yes',
    minFundingAmount: 25000,
    maxFundingAmount: 500000,
    fundingPurposes: ['Expansion', 'Debt Refinancing', 'Marketing', 'Working Capital'],
    repaymentType: 'Long Term',
    rateTermsInfo: 'From 7.49% to 22.99% fixed APR',
    typicalTermRange: '6 months – 7 years',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_triton_equipment',
    name: 'Commercial Equipment Lease & Financing',
    provider: 'Triton Capital',
    category: 'Equipment Financing',
    description: 'Equipment-backed loans and lease agreements allowing the purchased machinery or hardware to serve as primary security.',
    websiteUrl: 'https://tritoncapital.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 350000,
    fundingPurposes: ['Equipment', 'Vehicle'],
    repaymentType: 'Medium Term',
    rateTermsInfo: 'From 6.99% APR (determined by equipment type & depreciation profile)',
    typicalTermRange: '24–60 months',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_currency_finance',
    name: 'Heavy Equipment & Machinery Capital',
    provider: 'Currency Finance',
    category: 'Equipment Financing',
    description: 'Specialized commercial machinery, fleet vehicles, and hardware financing where the acquired asset secures the loan with flexible term structures.',
    websiteUrl: 'https://www.gocurrency.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$75,000',
    minPersonalCredit: '600+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 500000,
    fundingPurposes: ['Equipment', 'Vehicle', 'Expansion'],
    repaymentType: 'Long Term',
    rateTermsInfo: 'Rates from 7.25% fixed APR',
    typicalTermRange: '36–72 months',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_lendio_sba',
    name: 'SBA 7(a) & Express Loan Marketplace',
    provider: 'Lendio',
    category: 'SBA-related Financing',
    description: 'Government-backed low-rate financing designed for established businesses seeking long amortization periods and large capital.',
    websiteUrl: 'https://lendio.com',
    affiliateUrl: 'https://lendio.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '680+',
    businessCreditRequired: 'yes',
    minFundingAmount: 30000,
    maxFundingAmount: 5000000,
    fundingPurposes: ['Expansion', 'Debt Refinancing', 'Business Acquisition'],
    repaymentType: 'Long Term',
    rateTermsInfo: 'Prime + 2.25% to 4.75% variable or fixed cap',
    typicalTermRange: '10–25 years monthly amortization',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_smartbiz_sba',
    name: 'SBA Working Capital & Debt Refi',
    provider: 'SmartBiz',
    category: 'SBA-related Financing',
    description: 'Streamlined digital SBA 7(a) loan matching with prime interest rates and 10-year monthly repayment terms for qualified operating businesses.',
    websiteUrl: 'https://www.smartbizloans.com',
    affiliateUrl: 'https://www.smartbizloans.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '680+',
    businessCreditRequired: 'yes',
    minFundingAmount: 30000,
    maxFundingAmount: 350000,
    fundingPurposes: ['Working Capital', 'Debt Refinancing', 'Expansion'],
    repaymentType: 'Long Term',
    rateTermsInfo: 'Prime + 2.75% to 3.75%',
    typicalTermRange: '10 years (fully amortizing)',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_national_funding',
    name: 'Working Capital Short-Term Advance',
    provider: 'National Funding',
    category: 'Working Capital',
    description: 'Fast evaluation working capital suited for newer operations requiring quick bridge liquidity without lengthy underwriting.',
    websiteUrl: 'https://nationalfunding.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 100000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Marketing'],
    repaymentType: 'Short Term',
    rateTermsInfo: 'Factor rate starting at 1.15 (daily or weekly ACH deduction)',
    typicalTermRange: '4–12 months',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_rapid_finance',
    name: 'Small Business Working Capital',
    provider: 'Rapid Finance',
    category: 'Working Capital',
    description: 'Customizable commercial working capital advances sized to your daily or weekly deposit volumes, providing rapid cash infusions.',
    websiteUrl: 'https://www.rapidfinance.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: '550+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 200000,
    fundingPurposes: ['Working Capital', 'Inventory', 'Payroll'],
    repaymentType: 'Short Term',
    rateTermsInfo: 'Factor rate from 1.14–1.28 based on bank cash flow',
    typicalTermRange: '3–18 months',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_fundthrough_invoicing',
    name: 'Invoice Factoring & Accounts Receivable Financing',
    provider: 'FundThrough',
    category: 'Invoice Financing',
    description: 'Unlock working capital trapped in unpaid B2B net-30 or net-60 invoices without waiting for client payment cycles.',
    websiteUrl: 'https://www.fundthrough.com',
    affiliateUrl: 'https://www.fundthrough.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 0,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 10000,
    maxFundingAmount: 2000000,
    fundingPurposes: ['Working Capital', 'Cash Flow Buffer', 'Payroll'],
    repaymentType: 'Short Term',
    rateTermsInfo: 'From 1.75%–3.5% per 30-day invoice period',
    typicalTermRange: '30–90 days (matched to customer payment terms)',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_capital_card',
    name: 'Business Credit Card for LLCs',
    provider: 'Capital on Tap',
    category: 'Business Credit Card',
    description: 'Dedicated corporate credit card with flexible limits up to $50,000, cash back terms, and commercial credit reporting.',
    websiteUrl: 'https://capitalontap.com',
    affiliateUrl: 'https://capitalontap.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: '650+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 1000,
    maxFundingAmount: 50000,
    fundingPurposes: ['Everyday Expenses', 'Working Capital', 'Marketing'],
    repaymentType: 'Revolving',
    rateTermsInfo: '9.99% – 29.99% APR variable (grace period on full balances)',
    typicalTermRange: 'Revolving line',
    lastReviewedDate: '2026-09-01',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_wayflyer_rbf',
    name: 'Revenue-Based Growth Financing',
    provider: 'Wayflyer',
    category: 'Revenue-based Financing',
    description: 'Non-dilutive growth capital for e-commerce and direct-to-consumer businesses, repaid through a flexible percentage of daily online sales.',
    websiteUrl: 'https://www.wayflyer.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 10000,
    maxFundingAmount: 500000,
    fundingPurposes: ['Marketing', 'Inventory', 'Working Capital'],
    repaymentType: 'Short Term',
    rateTermsInfo: 'Fixed fee from 4%–10% of total capital (no compounding interest)',
    typicalTermRange: '3–12 months flexible remittance',
    lastReviewedDate: '2026-09-05',
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  // =========================================================================
  // CURATED LEGITIMATE SMALL BUSINESS GRANTS
  // =========================================================================
  {
    id: 'fund_grant_amber',
    name: 'Amber Grant for Women Entrepreneurs',
    provider: 'WomensNet',
    category: 'Grant',
    description: 'Monthly $10,000 grants plus $25,000 annual year-end grants awarded to female entrepreneurs to launch, expand, and scale their businesses.',
    websiteUrl: 'https://ambergrantsforwomen.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 0,
    minAnnualRevenue: '$0',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 10000,
    maxFundingAmount: 25000,
    fundingPurposes: ['Expansion', 'Equipment', 'Marketing', 'Working Capital'],
    repaymentType: 'Grant',
    rateTermsInfo: '$0 Repayment • 100% Non-dilutive grant funds',
    typicalTermRange: 'Non-repayable grant',
    grantDeadline: 'Monthly rolling deadline (final day of each month)',
    grantAmount: '$10,000 monthly / $25,000 annual',
    eligibilityNotes: 'Women-owned businesses (at least 51% female ownership), US & Canada nationwide',
    locationRestrictions: 'US and Canada nationwide',
    lastReviewedDate: '2026-09-06',
    createdAt: '2026-09-06T00:00:00.000Z',
    updatedAt: '2026-09-06T00:00:00.000Z',
  },
  {
    id: 'fund_grant_fedex',
    name: 'FedEx Small Business Grant Contest',
    provider: 'FedEx',
    category: 'Grant',
    description: 'Annual competitive small business grant awarding grand prize funds and FedEx Office print/shipping credits to innovative operating companies.',
    websiteUrl: 'https://www.fedex.com/en-us/small-business/grant-contest.html',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$0',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 20000,
    maxFundingAmount: 30000,
    fundingPurposes: ['Expansion', 'Marketing', 'Working Capital'],
    repaymentType: 'Grant',
    rateTermsInfo: '$0 Repayment • 100% Non-dilutive grant award',
    typicalTermRange: 'Non-repayable grant',
    grantDeadline: 'Annual cycle (Spring application window)',
    grantAmount: '$30,000 Grand Prize + $1,000 FedEx Office credit',
    eligibilityNotes: 'For-profit operating business, active commercial shipping account, US-based',
    locationRestrictions: 'United States nationwide',
    lastReviewedDate: '2026-09-06',
    createdAt: '2026-09-06T00:00:00.000Z',
    updatedAt: '2026-09-06T00:00:00.000Z',
  },
  {
    id: 'fund_grant_fast_break',
    name: 'Fast Break for Small Business Grant',
    provider: 'LegalZoom & NBA / WNBA',
    category: 'Grant',
    description: 'Initiative providing $10,000 grants plus $500 in LegalZoom services to underrepresented small business owners nationwide.',
    websiteUrl: 'https://www.legalzoom.com/fastbreakforsmallbusiness',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$0',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 10000,
    maxFundingAmount: 10000,
    fundingPurposes: ['Working Capital', 'Expansion', 'Everyday Expenses'],
    repaymentType: 'Grant',
    rateTermsInfo: '$0 Repayment • Non-repayable community award',
    typicalTermRange: 'Non-repayable grant',
    grantDeadline: 'Biannual seasonal application cycles',
    grantAmount: '$10,000 cash grant + $500 LegalZoom credit',
    eligibilityNotes: 'For-profit small businesses, in operation for 3+ months, under $1M annual revenue',
    locationRestrictions: 'US nationwide (all 50 states and DC)',
    lastReviewedDate: '2026-09-06',
    createdAt: '2026-09-06T00:00:00.000Z',
    updatedAt: '2026-09-06T00:00:00.000Z',
  },
  {
    id: 'fund_grant_nav_quarterly',
    name: 'Nav Small Business Grant',
    provider: 'Nav',
    category: 'Grant',
    description: 'Quarterly grant competition awarding capital to small businesses that demonstrate a clear milestone they need financing to overcome.',
    websiteUrl: 'https://www.nav.com/small-business-grant/',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 0,
    minAnnualRevenue: '$0',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 10000,
    fundingPurposes: ['Equipment', 'Marketing', 'Expansion'],
    repaymentType: 'Grant',
    rateTermsInfo: '$0 Repayment • Free community grant',
    typicalTermRange: 'Non-repayable grant',
    grantDeadline: 'Quarterly cycle (Q1, Q2, Q3, Q4 cohorts)',
    grantAmount: '$10,000 Grand Prize / $5,000 Runner-up',
    eligibilityNotes: 'Open to US small businesses and startups with a free Nav account',
    locationRestrictions: 'US nationwide',
    lastReviewedDate: '2026-09-06',
    createdAt: '2026-09-06T00:00:00.000Z',
    updatedAt: '2026-09-06T00:00:00.000Z',
  },
];
