import type { FundingProduct } from '../../types/fundingProduct';

export const INITIAL_FUNDING_PRODUCTS: FundingProduct[] = [
  {
    id: 'fund_prod_fundbox_loc',
    name: 'Revolving Business Line of Credit',
    provider: 'Fundbox',
    category: 'Business Line of Credit',
    description: 'Flexible revolving credit line to bridge cash flow gaps, finance invoices, and cover operational payroll.',
    websiteUrl: 'https://fundbox.com',
    affiliateUrl: 'https://fundbox.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: '600+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 150000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Inventory'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_bluevine_loc',
    name: 'Fast-Draw Business Line of Credit',
    provider: 'Bluevine',
    category: 'Business Line of Credit',
    description: 'On-demand revolving credit access with 24-hour approval decisions, transparent simple-interest rates, and weekly or monthly repayment flexibility.',
    websiteUrl: 'https://www.bluevine.com',
    affiliateUrl: 'https://www.bluevine.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '625+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 6000,
    maxFundingAmount: 250000,
    fundingPurposes: ['Working Capital', 'Cash Flow Buffer', 'Inventory', 'Payroll'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_ondeck_term',
    name: 'Fixed-Rate Small Business Term Loan',
    provider: 'OnDeck',
    category: 'Term Loan',
    description: 'Short-to-medium term business loan with fixed repayment schedules for inventory expansion and bulk asset acquisitions.',
    websiteUrl: 'https://ondeck.com',
    affiliateUrl: 'https://ondeck.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 12,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '625+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 250000,
    fundingPurposes: ['Expansion', 'Inventory', 'Working Capital'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_funding_circle',
    name: 'Commercial Expansion Term Loan',
    provider: 'Funding Circle',
    category: 'Term Loan',
    description: 'Fixed-rate term financing with 6-month to 7-year terms and zero prepayment penalties, ideal for established business growth and expansion.',
    websiteUrl: 'https://www.fundingcircle.com',
    affiliateUrl: 'https://www.fundingcircle.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$150,000',
    minPersonalCredit: '660+',
    businessCreditRequired: 'yes',
    minFundingAmount: 25000,
    maxFundingAmount: 500000,
    fundingPurposes: ['Expansion', 'Debt Refinancing', 'Marketing', 'Working Capital'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_triton_equipment',
    name: 'Commercial Equipment Lease & Financing',
    provider: 'Triton Capital',
    category: 'Equipment Financing',
    description: 'Equipment-backed loans and lease agreements allowing the purchased machinery or hardware to serve as primary security.',
    websiteUrl: 'https://tritoncapital.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 10000,
    maxFundingAmount: 350000,
    fundingPurposes: ['Equipment', 'Vehicle'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_currency_finance',
    name: 'Heavy Equipment & Machinery Capital',
    provider: 'Currency Finance',
    category: 'Equipment Financing',
    description: 'Specialized commercial machinery, fleet vehicles, and hardware financing where the acquired asset secures the loan with flexible term structures.',
    websiteUrl: 'https://www.gocurrency.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$75,000',
    minPersonalCredit: '600+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 500000,
    fundingPurposes: ['Equipment', 'Vehicle', 'Expansion'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_lendio_sba',
    name: 'SBA 7(a) & Express Loan Marketplace',
    provider: 'Lendio',
    category: 'SBA-related Financing',
    description: 'Government-backed low-rate financing designed for established businesses seeking long amortization periods and large capital.',
    websiteUrl: 'https://lendio.com',
    affiliateUrl: 'https://lendio.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '680+',
    businessCreditRequired: 'yes',
    minFundingAmount: 30000,
    maxFundingAmount: 5000000,
    fundingPurposes: ['Expansion', 'Debt Refinancing', 'Business Acquisition'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_smartbiz_sba',
    name: 'SBA Working Capital & Debt Refi',
    provider: 'SmartBiz',
    category: 'SBA-related Financing',
    description: 'Streamlined digital SBA 7(a) loan matching with prime interest rates and 10-year monthly repayment terms for qualified operating businesses.',
    websiteUrl: 'https://www.smartbizloans.com',
    affiliateUrl: 'https://www.smartbizloans.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 24,
    minAnnualRevenue: '$100,000',
    minPersonalCredit: '680+',
    businessCreditRequired: 'yes',
    minFundingAmount: 30000,
    maxFundingAmount: 350000,
    fundingPurposes: ['Working Capital', 'Debt Refinancing', 'Expansion'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_national_funding',
    name: 'Working Capital Short-Term Advance',
    provider: 'National Funding',
    category: 'Working Capital',
    description: 'Fast evaluation working capital suited for newer operations requiring quick bridge liquidity without lengthy underwriting.',
    websiteUrl: 'https://nationalfunding.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 100000,
    fundingPurposes: ['Working Capital', 'Payroll', 'Marketing'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'fund_prod_rapid_finance',
    name: 'Small Business Working Capital',
    provider: 'Rapid Finance',
    category: 'Working Capital',
    description: 'Customizable commercial working capital advances sized to your daily or weekly deposit volumes, providing rapid cash infusions.',
    websiteUrl: 'https://www.rapidfinance.com',
    affiliateUrl: '',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 3,
    minAnnualRevenue: '$50,000',
    minPersonalCredit: '550+',
    businessCreditRequired: 'no',
    minFundingAmount: 5000,
    maxFundingAmount: 200000,
    fundingPurposes: ['Working Capital', 'Inventory', 'Payroll'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_fundthrough_invoicing',
    name: 'Invoice Factoring & Accounts Receivable Financing',
    provider: 'FundThrough',
    category: 'Other',
    description: 'Unlock working capital trapped in unpaid B2B net-30 or net-60 invoices without waiting for client payment cycles.',
    websiteUrl: 'https://www.fundthrough.com',
    affiliateUrl: 'https://www.fundthrough.com?ref=crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: false,
    priority: 2,
    minBusinessAgeMonths: 0,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: 'None',
    businessCreditRequired: 'no',
    minFundingAmount: 10000,
    maxFundingAmount: 2000000,
    fundingPurposes: ['Working Capital', 'Cash Flow Buffer', 'Payroll'],
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-05T00:00:00.000Z',
  },
  {
    id: 'fund_prod_capital_card',
    name: 'Business Credit Card for LLCs',
    provider: 'Capital on Tap',
    category: 'Business Credit Card',
    description: 'Dedicated corporate credit card with flexible limits up to $50,000, cash back terms, and commercial credit reporting.',
    websiteUrl: 'https://capitalontap.com',
    affiliateUrl: 'https://capitalontap.com/partner/crediqly',
    affiliateEnabled: false,
    status: 'active',
    featured: true,
    priority: 1,
    minBusinessAgeMonths: 6,
    minAnnualRevenue: '$25,000',
    minPersonalCredit: '650+',
    businessCreditRequired: 'not_specified',
    minFundingAmount: 1000,
    maxFundingAmount: 50000,
    fundingPurposes: ['Everyday Expenses', 'Working Capital', 'Marketing'],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
];
