import { Product } from '@/types/product';

export const DEFAULT_PRODUCTS: Product[] = [
  // ============================================================================
  // 1. BUSINESS CREDIT BUILDERS
  // ============================================================================
  {
    id: 'prod_ecredable',
    name: 'eCredable Business Lift',
    slug: 'ecredable-business-lift',
    category: 'business_credit_builders',
    shortDescription:
      'Reports recurring business utility, phone, internet, and office rent expenses to commercial bureaus.',
    description:
      'eCredable Business Lift allows small business owners to link and report recurring business accounts such as power, water, mobile phones, internet, and commercial office rent directly to Dun & Bradstreet, Experian Business, and Equifax Business. It can report up to 24 months of historical payment data for eligible utility accounts.',
    websiteUrl: 'https://www.ecredable.com',
    affiliateUrl: 'https://www.ecredable.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Vendor Reporting & Utility Link',
    terms: 'Monthly Reporting',
    annualFee: '$0 (Monthly plan)',
    minimumPurchase: 'Subscription plan',
    subscriptionRequired: true,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No personal credit check)',
    potentialFit: 'Startups and new entities needing fast bureau trade experiences from existing utility bills.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_nav_prime',
    name: 'Nav Prime',
    slug: 'nav-prime',
    category: 'business_credit_builders',
    shortDescription:
      'Provides dual tradeline reporting to major commercial credit bureaus alongside credit monitoring.',
    description:
      'Nav Prime offers automated monthly tradeline reporting to Dun & Bradstreet, Experian Business, and Equifax Business. You receive detailed multi-bureau credit reports, cash flow scoring, and optional Nav Debit card payment history reporting.',
    websiteUrl: 'https://www.nav.com',
    affiliateUrl: 'https://www.nav.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Tradeline & Credit Monitoring Service',
    terms: 'Monthly Tradeline',
    annualFee: '$0 (Monthly membership)',
    minimumPurchase: 'Monthly membership fee',
    subscriptionRequired: true,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No hard pull)',
    potentialFit: 'Businesses seeking verified dual reporting and comprehensive commercial bureau monitoring.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_credit_strong',
    name: 'Credit Strong Business',
    slug: 'credit-strong-business',
    category: 'business_credit_builders',
    shortDescription:
      'Commercial installment credit-builder loan reporting payment history without a personal guarantee.',
    description:
      'Credit Strong Business offers commercial installment accounts through an FDIC-insured bank. Your monthly principal payments build savings in a locked certificate of deposit while building commercial installment payment history with Equifax Business, PayNet, and SBFE.',
    websiteUrl: 'https://www.creditstrong.com',
    affiliateUrl: 'https://www.creditstrong.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Equifax Business', 'PayNet', 'SBFE'],
    productType: 'Commercial Installment Builder',
    terms: 'Commercial Installment',
    annualFee: '$0 (Loan installment plan)',
    minimumPurchase: '$115/mo loan installment',
    subscriptionRequired: false,
    typicalBusinessAge: '3+ months',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No personal credit check)',
    potentialFit: 'Businesses wanting to establish installment loan history alongside trade vendor accounts.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 2. NET-30 VENDORS
  // ============================================================================
  {
    id: 'prod_quill',
    name: 'Quill Office Supplies',
    slug: 'quill-net-30',
    category: 'net_30',
    shortDescription:
      'Established commercial vendor offering net-30 invoice terms for office and cleaning supplies.',
    description:
      'Quill provides small businesses with commercial credit lines for office supplies, safety gear, paper, and breakroom essentials. Generally requires 1 to 2 prepaid orders before extending 30-day invoice billing, reporting monthly payment experiences to Dun & Bradstreet.',
    websiteUrl: 'https://www.quill.com',
    affiliateUrl: 'https://www.quill.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet'],
    productType: 'Vendor Trade Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$100 initial invoice order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Businesses purchasing regular office, breakroom, and packaging supplies.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_uline',
    name: 'Uline Shipping Supplies',
    slug: 'uline-net-30',
    category: 'net_30',
    shortDescription:
      'Leading packaging and warehouse supplier providing net-30 commercial invoicing terms.',
    description:
      'Uline is a major North American distributor of shipping, packaging, and industrial supplies. Eligible commercial accounts can purchase inventory on net-30 billing terms, with payment experiences reported to Dun & Bradstreet and Experian Business.',
    websiteUrl: 'https://www.uline.com',
    affiliateUrl: 'https://www.uline.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business'],
    productType: 'Vendor Trade Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: 'Varies by invoice order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'E-commerce, logistics, and retail businesses needing shipping boxes and warehouse supplies.',
    recommendedStage: 'building',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_grainger',
    name: 'Grainger Industrial Supply',
    slug: 'grainger-net-30',
    category: 'net_30',
    shortDescription:
      'Major industrial, maintenance, and safety supplier providing net-30 trade credit lines.',
    description:
      'Grainger provides commercial accounts with access to facilities maintenance, tools, safety gear, and industrial equipment. Once an open account is approved, invoice payments on net-30 terms are reported to Dun & Bradstreet.',
    websiteUrl: 'https://www.grainger.com',
    affiliateUrl: 'https://www.grainger.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet'],
    productType: 'Vendor Trade Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: 'Varies by order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Maintenance, construction, and operational teams needing equipment and safety inventory.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_crown',
    name: 'Crown Office Supplies',
    slug: 'crown-office-supplies',
    category: 'net_30',
    shortDescription:
      'Tier-1 vendor account providing office accessories and tech accessories with bureau reporting.',
    description:
      'Crown Office Supplies extends commercial credit lines to newly formed and existing businesses for stationery, electronics, and office accessories. Invoices paid on net-30 terms are reported across major business credit bureaus.',
    websiteUrl: 'https://crownofficesupplies.com',
    affiliateUrl: 'https://crownofficesupplies.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Tier-1 Vendor Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$30 minimum product order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'New businesses seeking an entry-level tier-1 trade line with multi-bureau reporting.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_summa',
    name: 'Summa Office Supplies',
    slug: 'summa-office-supplies',
    category: 'net_30',
    shortDescription:
      'Vendor credit account providing commercial stationery, digital products, and supplies.',
    description:
      'Summa Office Supplies provides straightforward tier-1 vendor credit lines to small businesses and startups. Requires an initial qualifying purchase and reports payment history to commercial credit databases.',
    websiteUrl: 'https://summaofficesupplies.com',
    affiliateUrl: 'https://summaofficesupplies.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Equifax Business'],
    productType: 'Tier-1 Vendor Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$75 minimum order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Startups requiring commercial stationery with minimal documentation hurdles.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_ceo_creative',
    name: 'The CEO Creative',
    slug: 'the-ceo-creative-net-30',
    category: 'net_30',
    shortDescription:
      'Branding, custom apparel, and office essentials supplier extending net-30 terms.',
    description:
      'The CEO Creative offers small businesses custom branding, business cards, merchandise, and office products on net-30 terms. Accounts with qualifying purchases report payment experiences to CreditSafe and Equifax Business.',
    websiteUrl: 'https://theceocreative.com',
    affiliateUrl: 'https://theceocreative.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe', 'Equifax Business'],
    productType: 'Vendor Trade Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$40 minimum purchase',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Companies seeking custom branded merchandise and early commercial tradelines.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_office_garner',
    name: 'Office Garner',
    slug: 'office-garner-net-30',
    category: 'net_30',
    shortDescription:
      'Office technology and desk accessories vendor offering net-30 billing terms.',
    description:
      'Office Garner provides small businesses with electronic cables, ergonomic desk tools, and office accessories on 30-day terms, reporting timely commercial payments to Equifax Business.',
    websiteUrl: 'https://officegarner.com',
    affiliateUrl: 'https://officegarner.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Equifax Business'],
    productType: 'Tier-1 Vendor Credit (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$45 minimum order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Businesses wanting accessible tech supplies to establish Equifax trade depth.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_sns',
    name: 'Strategic Network Solutions',
    slug: 'strategic-network-solutions-net-30',
    category: 'net_30',
    shortDescription:
      'IT hardware, digital security software, and cloud services on commercial net-30 terms.',
    description:
      'Strategic Network Solutions supplies businesses with technology hardware, cybersecurity products, and software licensing under 30-day terms, reporting monthly to CreditSafe and Experian Business.',
    websiteUrl: 'https://stntsol.com',
    affiliateUrl: 'https://stntsol.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe', 'Experian Business'],
    productType: 'IT Services Vendor (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$60 minimum purchase',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Tech-focused and remote businesses needing computer accessories and digital services.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_jj_gold',
    name: 'JJ Gold International',
    slug: 'jj-gold-net-30',
    category: 'net_30',
    shortDescription:
      'Corporate gifting, decor, and specialty accessories vendor offering net-30 terms.',
    description:
      'JJ Gold International provides business decor, gift sets, and corporate promotional items on net-30 billing terms, reporting verified payment experiences to Dun & Bradstreet and Equifax Business.',
    websiteUrl: 'https://jjgold.com',
    affiliateUrl: 'https://jjgold.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Equifax Business'],
    productType: 'Corporate Gifting Vendor (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: '$50 minimum order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Businesses purchasing client appreciation gifts and office decorative items.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_shirtsy',
    name: 'Shirtsy Direct',
    slug: 'shirtsy-net-30',
    category: 'net_30',
    shortDescription:
      'On-demand custom corporate apparel and printing with net-30 terms.',
    description:
      'Shirtsy provides on-demand custom branded shirts, uniforms, and promotional merchandise on net-30 commercial payment terms. Reports commercial trade experiences to CreditSafe.',
    websiteUrl: 'https://shirtsy.com',
    affiliateUrl: 'https://shirtsy.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe'],
    productType: 'Custom Apparel Vendor (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: 'Eligible apparel order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Teams ordering uniforms, employee merch, and custom event gear.',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },

  // ============================================================================
  // 3. NET-60 ACCOUNTS
  // ============================================================================
  {
    id: 'prod_creative_analytics',
    name: 'Creative Analytics',
    slug: 'creative-analytics-net-60',
    category: 'net_60',
    shortDescription:
      'Digital consulting and web design services offering 60-day commercial invoice terms.',
    description:
      'Creative Analytics extends 60-day vendor trade credit for digital design, SEO, and consulting services, reporting trade experiences to commercial credit bureaus to establish intermediate credit depth.',
    websiteUrl: 'https://creativeanalyticsdc.com',
    affiliateUrl: 'https://creativeanalyticsdc.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe', 'Equifax Business'],
    productType: 'Vendor Trade Credit (Net-60)',
    terms: 'Net-60',
    annualFee: '$0',
    minimumPurchase: 'Eligible service invoice',
    subscriptionRequired: false,
    typicalBusinessAge: '6+ months',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Businesses seeking extended payment terms for professional digital services.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_wise_plans',
    name: 'Wise Business Plans',
    slug: 'wise-business-plans-net-30',
    category: 'net_30',
    shortDescription:
      'Professional business planning, market feasibility, and corporate consulting with commercial terms.',
    description:
      'Wise Business Plans provides professional custom business plans for bank financing, investor pitch decks, and commercial market research with invoice terms, reporting payment history to CreditSafe.',
    websiteUrl: 'https://wisebusinessplans.com',
    affiliateUrl: 'https://wisebusinessplans.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe'],
    productType: 'Professional Services (Net-30)',
    terms: 'Net-30',
    annualFee: '$0',
    minimumPurchase: 'Service invoice',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Businesses preparing documentation for SBA financing or commercial loan applications.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },

  // ============================================================================
  // 4. BUSINESS CREDIT CARDS
  // ============================================================================
  {
    id: 'prod_ramp',
    name: 'Ramp Corporate Card',
    slug: 'ramp-corporate-card',
    category: 'business_credit_cards',
    shortDescription:
      'Modern corporate card with 1.5% cashback, expense automation, and zero personal guarantee.',
    description:
      'Ramp provides commercial corporate charge cards for incorporated entities based on commercial cash balances and operating cash flow rather than personal FICO scores. Offers 1.5% cashback on all purchases, real-time receipt matching, and zero personal guarantee requirements.',
    websiteUrl: 'https://ramp.com',
    affiliateUrl: 'https://ramp.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet'],
    productType: 'Corporate Charge Card',
    terms: 'Monthly Charge Card',
    annualFee: '$0',
    introOffer: '1.5% cashback on all card spend with automated expense management',
    potentialFundingRange: '$10K–$250K+',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: '6+ months (Requires $25k+ bank balance)',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Underwritten by business cash flow)',
    potentialFit: 'Incorporated businesses with strong operating balances seeking zero personal guarantee.',
    recommendedStage: 'optimization',
    status: 'active',
    featured: true,
    priority: 1,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_bill_divvy',
    name: 'BILL Spend & Expense',
    slug: 'bill-spend-and-expense',
    category: 'business_credit_cards',
    shortDescription:
      'Flexible business credit lines and corporate expense cards for growing small businesses.',
    description:
      'BILL Spend & Expense combines free automated expense management software with commercial credit lines from $500 to $5M. Reports payment history to Experian Business and the Small Business Financial Exchange (SBFE).',
    websiteUrl: 'https://www.bill.com',
    affiliateUrl: 'https://www.bill.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'SBFE'],
    productType: 'Business Credit Line & Card',
    terms: 'Revolving Line & Card',
    annualFee: '$0',
    introOffer: 'Flexible credit limits from $500 to $5M; automated team budgeting',
    potentialFundingRange: '$5K–$100K+',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No strict minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Fair to Good (620+)',
    potentialFit: 'Businesses wanting credit lines alongside free automated expense management software.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_brex',
    name: 'Brex Card for Startups',
    slug: 'brex-corporate-card',
    category: 'business_credit_cards',
    shortDescription:
      'High-limit corporate card designed for funded startups and scaling businesses with no personal guarantee.',
    description:
      'Brex provides corporate cards with dynamic limits scaled directly to bank account cash balances. Does not require a personal guarantee or personal credit inquiry, and reports commercial payment history to Dun & Bradstreet and Experian Business.',
    websiteUrl: 'https://www.brex.com',
    affiliateUrl: 'https://www.brex.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet'],
    productType: 'Corporate Charge Card',
    terms: 'Monthly Charge Card',
    annualFee: '$0',
    introOffer: 'Up to 7X reward points on dining and travel; dynamic balance-based limits',
    potentialFundingRange: '$20K–$500K+',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum (Requires $50k+ cash balance)',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Funded tech startups and high-balance scaling businesses seeking high charge limits.',
    recommendedStage: 'optimization',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_chase_ink_cash',
    name: 'Chase Ink Business Cash',
    slug: 'chase-ink-business-cash',
    category: 'business_credit_cards',
    shortDescription:
      '5% cash back on office supplies and internet services with a $0 annual fee and 0% intro APR.',
    description:
      'The Chase Ink Business Cash credit card offers 5% cash back on the first $25,000 spent in combined purchases at office supply stores and on internet, cable, and phone services each account anniversary year. Reports commercial activity to commercial credit bureaus.',
    websiteUrl: 'https://creditcards.chase.com',
    affiliateUrl: 'https://creditcards.chase.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Equifax Business', 'Dun & Bradstreet'],
    productType: 'Cash Back Business Card',
    terms: 'Revolving Business Credit Card',
    annualFee: '$0',
    introOffer: '5% cash back in key categories; 0% intro APR on purchases for 12 months',
    potentialFundingRange: '$5K–$50K',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Good to Excellent (680+)',
    potentialFit: 'Small businesses seeking top-tier cash rewards on recurring office and telecom expenses.',
    recommendedStage: 'building',
    status: 'active',
    featured: true,
    priority: 1,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_spark_classic',
    name: 'Capital One Spark Classic for Business',
    slug: 'capital-one-spark-classic',
    category: 'business_credit_cards',
    shortDescription:
      'Revolving business card designed for credit building with fair personal credit and 1% cash back.',
    description:
      'Capital One Spark Classic is tailored for small business owners building or rebuilding credit. It requires only fair personal credit, charges $0 annual fee, earns unlimited 1% cash back on every purchase, and reports to major commercial credit bureaus to help build business credit.',
    websiteUrl: 'https://www.capitalone.com',
    affiliateUrl: 'https://www.capitalone.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet', 'Equifax Business'],
    productType: 'Credit-Building Business Card',
    terms: 'Revolving Business Credit Card',
    annualFee: '$0',
    introOffer: 'Unlimited 1% cash back on all purchases with credit-building reporting',
    potentialFundingRange: '$1K–$15K',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Fair (580–669)',
    potentialFit: 'Business owners with fair personal credit looking to establish revolving commercial trade lines.',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_amex_blue_plus',
    name: 'American Express Blue Business Plus',
    slug: 'amex-blue-business-plus',
    category: 'business_credit_cards',
    shortDescription:
      '2X Membership Rewards points on everyday business purchases up to $50K with a $0 annual fee.',
    description:
      'The American Express Blue Business Plus Credit Card earns 2X points on everyday business purchases up to $50,000 per calendar year, then 1X points thereafter. Features expanded buying power to spend beyond credit limit based on card usage and payment history.',
    websiteUrl: 'https://www.americanexpress.com',
    affiliateUrl: 'https://www.americanexpress.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet', 'SBFE'],
    productType: 'Rewards Business Credit Card',
    terms: 'Revolving Business Credit Card',
    annualFee: '$0',
    introOffer: '2X points on first $50,000/yr; 0% intro APR on purchases for 12 months',
    potentialFundingRange: '$5K–$50K+',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Good to Excellent (670+)',
    potentialFit: 'Businesses seeking flexible purchasing power and points on everyday operating expenses.',
    recommendedStage: 'optimization',
    status: 'active',
    featured: true,
    priority: 1,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_bofa_customized_cash',
    name: 'Bank of America Business Advantage Customized Cash',
    slug: 'bofa-business-advantage-cash',
    category: 'business_credit_cards',
    shortDescription:
      '3% cash back in the category of your choice and 2% on dining with $0 annual fee.',
    description:
      'Bank of America Business Advantage Customized Cash Rewards allows owners to choose their 3% cash back category (such as gas, office supplies, travel, or computer services) and earn 2% cash back on dining on the first $50,000 in combined spending annually.',
    websiteUrl: 'https://www.bankofamerica.com',
    affiliateUrl: 'https://www.bankofamerica.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Equifax Business', 'Dun & Bradstreet'],
    productType: 'Cash Rewards Business Card',
    terms: 'Revolving Business Credit Card',
    annualFee: '$0',
    introOffer: '3% cash back on category of choice; 0% intro APR on purchases for 9 billing cycles',
    potentialFundingRange: '$3K–$35K',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Good to Excellent (680+)',
    potentialFit: 'Established businesses looking to align card cash back with their largest spending category.',
    recommendedStage: 'optimization',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'prod_torpago_card',
    name: 'Torpago Commercial Card',
    slug: 'torpago-commercial-card',
    category: 'business_credit_cards',
    shortDescription:
      'Revenue-based corporate card with no personal guarantee and automated spend management.',
    description:
      'Torpago provides corporate cards underwritten through business revenue and commercial checking cash flows rather than personal credit checks. Features granular team spending rules, real-time receipt capture, and commercial bureau reporting.',
    websiteUrl: 'https://torpago.com',
    affiliateUrl: 'https://torpago.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet'],
    productType: 'Corporate Charge Card',
    terms: 'Commercial Charge Card',
    annualFee: '$0',
    introOffer: 'No personal guarantee; limits dynamically sized to business monthly cash receipts',
    potentialFundingRange: '$10K–$150K',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: '3+ months (Requires $10k+ monthly deposits)',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Underwritten by business revenue)',
    potentialFit: 'Operating businesses generating $10k+/mo wanting corporate credit without personal guarantee.',
    recommendedStage: 'optimization',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
  },

  // ============================================================================
  // 5. BUSINESS BANKING
  // ============================================================================
  {
    id: 'prod_relay',
    name: 'Relay Financial',
    slug: 'relay-financial',
    category: 'business_banking',
    shortDescription:
      'Online business checking with zero monthly fees, up to 20 sub-accounts, and 50 debit cards.',
    description:
      'Relay is an online business banking platform built for small business teams. Open 100% online with zero account maintenance fees, zero minimum balance requirements, and support for Profit First cash allocation with multiple sub-checking accounts.',
    websiteUrl: 'https://www.relayfi.com',
    affiliateUrl: 'https://www.relayfi.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking Account',
    terms: 'Commercial Checking',
    annualFee: '$0',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Soft identity check only)',
    potentialFit: 'Startups and LLCs establishing their first dedicated business bank account.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    priority: 1,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_bluevine',
    name: 'Bluevine Business Checking',
    slug: 'bluevine-business-checking',
    category: 'business_banking',
    shortDescription:
      'High-yield commercial checking account offering up to 2.0% APY on eligible balances.',
    description:
      'Bluevine provides digital commercial checking designed for small businesses with no monthly maintenance fees, unlimited transactions, and interest-bearing sub-accounts with fast ACH and check processing.',
    websiteUrl: 'https://www.bluevine.com',
    affiliateUrl: 'https://www.bluevine.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking Account',
    terms: 'High-Yield Checking',
    annualFee: '$0',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Soft identity check)',
    potentialFit: 'Businesses seeking interest-bearing checking and streamlined bill payment workflows.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_mercury',
    name: 'Mercury Bank',
    slug: 'mercury',
    category: 'business_banking',
    shortDescription:
      'Modern commercial checking and treasury built for startups and incorporated entities.',
    description:
      'Mercury provides FDIC-insured checking and savings accounts through partner banks with no minimum balance requirements, free domestic and international wire transfers, and virtual cards.',
    websiteUrl: 'https://mercury.com',
    affiliateUrl: 'https://mercury.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking & Treasury',
    terms: 'Commercial Checking',
    annualFee: '$0',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Startups, digital agencies, and tech ventures needing multi-user banking and API integrations.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 6. BUSINESS SERVICES
  // ============================================================================
  {
    id: 'prod_northwest',
    name: 'Northwest Registered Agent',
    slug: 'northwest-registered-agent',
    category: 'business_services',
    shortDescription:
      'Professional registered agent and commercial address privacy service across all 50 states.',
    description:
      'Northwest Registered Agent provides professional commercial registered agent services, commercial address privacy, and state compliance filing for LLCs and Corporations across all 50 states.',
    websiteUrl: 'https://www.northwestregisteredagent.com',
    affiliateUrl: 'https://www.northwestregisteredagent.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Registered Agent & Privacy',
    terms: 'Annual Service',
    annualFee: '$125/yr',
    minimumPurchase: 'Varies by state package',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: false,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Entrepreneurs needing commercial entity address privacy and registered agent compliance.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    priority: 1,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_legalzoom',
    name: 'LegalZoom Business Services',
    slug: 'legalzoom-business-services',
    category: 'business_services',
    shortDescription:
      'Entity formation, federal EIN registration, and ongoing annual corporate compliance.',
    description:
      'LegalZoom helps entrepreneurs form LLCs, obtain federal EINs, draft operating agreements, and maintain annual Secretary of State regulatory filings.',
    websiteUrl: 'https://www.legalzoom.com',
    affiliateUrl: 'https://www.legalzoom.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Entity Formation & Compliance',
    terms: 'Entity Filing',
    annualFee: 'Varies by state',
    minimumPurchase: 'Varies by state filing fee',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: false,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    potentialFit: 'Founders registering an LLC or Corporation to obtain legal business entity status.',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    priority: 2,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
];
