import { Product } from '@/types/product';

export const DEFAULT_PRODUCTS: Product[] = [
  // ============================================================================
  // 1. BUSINESS CREDIT BUILDERS
  // ============================================================================
  {
    id: 'prod_ecredable',
    name: 'eCredable Business Lift',
    slug: 'ecredable-business-lift',
    category: 'business_credit_builders',
    shortDescription:
      'Reports recurring business utility, phone, internet, and office rent expenses to commercial bureaus.',
    description:
      'eCredable Business Lift allows small business owners to link and report recurring business accounts such as power, water, mobile phones, internet, and commercial office rent directly to Dun & Bradstreet, Experian Business, and Equifax Business. It can report up to 24 months of historical payment data for eligible utility accounts.',
    websiteUrl: 'https://www.ecredable.com',
    affiliateUrl: 'https://www.ecredable.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Vendor Reporting & Utility Link',
    minimumPurchase: 'Subscription plan',
    subscriptionRequired: true,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No personal credit check)',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_nav_prime',
    name: 'Nav Prime',
    slug: 'nav-prime',
    category: 'business_credit_builders',
    shortDescription:
      'Provides dual tradeline reporting to major commercial credit bureaus alongside credit monitoring.',
    description:
      'Nav Prime offers automated monthly tradeline reporting to Dun & Bradstreet, Experian Business, and Equifax Business. You receive detailed multi-bureau credit reports, cash flow scoring, and optional Nav Debit card payment history reporting.',
    websiteUrl: 'https://www.nav.com',
    affiliateUrl: 'https://www.nav.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Tradeline & Credit Monitoring Service',
    minimumPurchase: 'Monthly membership fee',
    subscriptionRequired: true,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No hard pull)',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_credit_strong',
    name: 'Credit Strong Business',
    slug: 'credit-strong-business',
    category: 'business_credit_builders',
    shortDescription:
      'Commercial installment credit-builder loan reporting payment history without a personal guarantee.',
    description:
      'Credit Strong Business offers commercial installment accounts through an FDIC-insured bank. Your monthly principal payments build savings in a locked certificate of deposit while building commercial installment payment history with Equifax Business, PayNet, and SBFE.',
    websiteUrl: 'https://www.creditstrong.com',
    affiliateUrl: 'https://www.creditstrong.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Equifax Business', 'PayNet', 'SBFE'],
    productType: 'Commercial Installment Builder',
    minimumPurchase: '$115/mo loan installment',
    subscriptionRequired: false,
    typicalBusinessAge: '3+ months',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (No personal credit check)',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 2. NET-30 ACCOUNTS
  // ============================================================================
  {
    id: 'prod_quill',
    name: 'Quill Office Supplies',
    slug: 'quill-net-30',
    category: 'net_30',
    shortDescription:
      'Established commercial vendor offering net-30 invoice terms for office and cleaning supplies.',
    description:
      'Quill provides small businesses with commercial credit lines for office supplies, safety gear, paper, and breakroom essentials. Generally requires 1 to 2 prepaid orders before extending 30-day invoice billing, reporting monthly payment experiences to Dun & Bradstreet.',
    websiteUrl: 'https://www.quill.com',
    affiliateUrl: 'https://www.quill.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet'],
    productType: 'Vendor Trade Credit (Net-30)',
    minimumPurchase: '$100 initial invoice order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_uline',
    name: 'Uline Shipping Supplies',
    slug: 'uline-net-30',
    category: 'net_30',
    shortDescription:
      'Leading packaging and warehouse supplier providing net-30 commercial invoicing terms.',
    description:
      'Uline is a major North American distributor of shipping, packaging, and industrial supplies. Eligible commercial accounts can purchase inventory on net-30 billing terms, with payment experiences reported to Dun & Bradstreet and Experian Business.',
    websiteUrl: 'https://www.uline.com',
    affiliateUrl: 'https://www.uline.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business'],
    productType: 'Vendor Trade Credit (Net-30)',
    minimumPurchase: 'Varies by invoice order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'building',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_crown',
    name: 'Crown Office Supplies',
    slug: 'crown-office-supplies',
    category: 'net_30',
    shortDescription:
      'Tier-1 vendor account providing office accessories and tech accessories with bureau reporting.',
    description:
      'Crown Office Supplies extends commercial credit lines to newly formed and existing businesses for stationery, electronics, and office accessories. Invoices paid on net-30 terms are reported across major business credit bureaus.',
    websiteUrl: 'https://crownofficesupplies.com',
    affiliateUrl: 'https://crownofficesupplies.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Experian Business', 'Equifax Business'],
    productType: 'Tier-1 Vendor Credit (Net-30)',
    minimumPurchase: '$30 minimum product order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'credit_foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_summa',
    name: 'Summa Office Supplies',
    slug: 'summa-office-supplies',
    category: 'net_30',
    shortDescription:
      'Vendor credit account providing commercial stationery, digital products, and supplies.',
    description:
      'Summa Office Supplies provides straightforward tier-1 vendor credit lines to small businesses and startups. Requires an initial qualifying purchase and reports payment history to commercial credit databases.',
    websiteUrl: 'https://summaofficesupplies.com',
    affiliateUrl: 'https://summaofficesupplies.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Dun & Bradstreet', 'Equifax Business'],
    productType: 'Tier-1 Vendor Credit (Net-30)',
    minimumPurchase: '$75 minimum order',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 3. NET-60 ACCOUNTS
  // ============================================================================
  {
    id: 'prod_creative_analytics',
    name: 'Creative Analytics',
    slug: 'creative-analytics-net-60',
    category: 'net_60',
    shortDescription:
      'Digital consulting and web design services offering 60-day commercial invoice terms.',
    description:
      'Creative Analytics extends 60-day vendor trade credit for digital design, SEO, and consulting services, reporting trade experiences to commercial credit bureaus to establish intermediate credit depth.',
    websiteUrl: 'https://creativeanalyticsdc.com',
    affiliateUrl: 'https://creativeanalyticsdc.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['CreditSafe', 'Equifax Business'],
    productType: 'Vendor Trade Credit (Net-60)',
    minimumPurchase: 'Eligible service invoice',
    subscriptionRequired: false,
    typicalBusinessAge: '6+ months',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 4. BUSINESS CREDIT CARDS
  // ============================================================================
  {
    id: 'prod_ramp',
    name: 'Ramp Corporate Card',
    slug: 'ramp-corporate-card',
    category: 'business_credit_cards',
    shortDescription:
      'Modern corporate card with 1.5% cashback, expense automation, and zero personal guarantee.',
    description:
      'Ramp provides commercial corporate charge cards for incorporated entities based on commercial cash balances and operating cash flow rather than personal FICO scores. Offers 1.5% cashback on all purchases, real-time receipt matching, and zero personal guarantee requirements.',
    websiteUrl: 'https://ramp.com',
    affiliateUrl: 'https://ramp.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet'],
    productType: 'Corporate Charge Card',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: '6+ months (Requires $25k+ bank balance)',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Underwritten by cash flow)',
    recommendedStage: 'optimization',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_bill_divvy',
    name: 'BILL Spend & Expense',
    slug: 'bill-spend-and-expense',
    category: 'business_credit_cards',
    shortDescription:
      'Flexible business credit lines and corporate expense cards for growing small businesses.',
    description:
      'BILL Spend & Expense (formerly Divvy) combines free automated expense management software with commercial credit lines from $500 to $5M. Reports payment history to Experian Business and the Small Business Financial Exchange (SBFE).',
    websiteUrl: 'https://www.bill.com',
    affiliateUrl: 'https://www.bill.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'SBFE'],
    productType: 'Business Credit Line & Card',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No strict minimum',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'yes',
    personalCreditRequirement: 'Fair to Good (620+)',
    recommendedStage: 'building',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_brex',
    name: 'Brex Card for Startups',
    slug: 'brex-corporate-card',
    category: 'business_credit_cards',
    shortDescription:
      'High-limit corporate card designed for funded startups and scaling businesses with no personal guarantee.',
    description:
      'Brex provides corporate cards with dynamic limits scaled directly to bank account cash balances. Does not require a personal guarantee or personal credit inquiry, and reports commercial payment history to Dun & Bradstreet and Experian Business.',
    websiteUrl: 'https://www.brex.com',
    affiliateUrl: 'https://www.brex.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: ['Experian Business', 'Dun & Bradstreet'],
    productType: 'Corporate Charge Card',
    minimumPurchase: 'None',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum (Requires $50k+ cash balance)',
    einRequired: true,
    businessBankAccountRequired: true,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'optimization',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 5. BUSINESS BANKING
  // ============================================================================
  {
    id: 'prod_relay',
    name: 'Relay Financial',
    slug: 'relay-financial-banking',
    category: 'business_banking',
    shortDescription:
      'Online business checking with zero monthly fees, up to 20 sub-accounts, and 50 debit cards.',
    description:
      'Relay is an online business banking platform built for small business teams. Open 100% online with zero account maintenance fees, zero minimum balance requirements, and support for Profit First cash allocation with multiple sub-checking accounts.',
    websiteUrl: 'https://www.relayfi.com',
    affiliateUrl: 'https://www.relayfi.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking Account',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Soft identity check only)',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_bluevine',
    name: 'Bluevine Business Checking',
    slug: 'bluevine-business-checking',
    category: 'business_banking',
    shortDescription:
      'High-yield commercial checking account offering up to 2.0% APY on eligible balances.',
    description:
      'Bluevine provides digital commercial checking designed for small businesses with no monthly maintenance fees, unlimited transactions, and interest-bearing sub-accounts with fast ACH and check processing.',
    websiteUrl: 'https://www.bluevine.com',
    affiliateUrl: 'https://www.bluevine.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking Account',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None (Soft identity check)',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_mercury',
    name: 'Mercury',
    slug: 'mercury-banking',
    category: 'business_banking',
    shortDescription:
      'Modern commercial checking and treasury built for startups and incorporated entities.',
    description:
      'Mercury provides FDIC-insured checking and savings accounts through partner banks with no minimum balance requirements, free domestic and international wire transfers, and virtual cards.',
    websiteUrl: 'https://mercury.com',
    affiliateUrl: 'https://mercury.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Commercial Checking & Treasury',
    minimumPurchase: 'No minimum deposit',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: true,
    businessBankAccountRequired: false,
    businessWebsiteRequired: true,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },

  // ============================================================================
  // 6. BUSINESS SERVICES
  // ============================================================================
  {
    id: 'prod_northwest',
    name: 'Northwest Registered Agent',
    slug: 'northwest-registered-agent',
    category: 'business_services',
    shortDescription:
      'Professional registered agent and commercial address privacy service across all 50 states.',
    description:
      'Northwest Registered Agent provides professional commercial registered agent services, commercial address privacy, and state compliance filing for LLCs and Corporations across all 50 states.',
    websiteUrl: 'https://www.northwestregisteredagent.com',
    affiliateUrl: 'https://www.northwestregisteredagent.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Registered Agent & Privacy',
    minimumPurchase: 'Varies by state package',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: false,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'foundation',
    status: 'active',
    featured: true,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
  {
    id: 'prod_legalzoom',
    name: 'LegalZoom Business Services',
    slug: 'legalzoom-business-services',
    category: 'business_services',
    shortDescription:
      'Entity formation, federal EIN registration, and ongoing annual corporate compliance.',
    description:
      'LegalZoom helps entrepreneurs form LLCs, obtain federal EINs, draft operating agreements, and maintain annual Secretary of State regulatory filings.',
    websiteUrl: 'https://www.legalzoom.com',
    affiliateUrl: 'https://www.legalzoom.com?ref=crediqly',
    affiliateEnabled: false,
    reportingBureaus: [],
    productType: 'Entity Formation & Compliance',
    minimumPurchase: 'Varies by state filing fee',
    subscriptionRequired: false,
    typicalBusinessAge: 'No minimum',
    einRequired: false,
    businessBankAccountRequired: false,
    businessWebsiteRequired: false,
    personalGuaranteeRequired: 'no',
    personalCreditRequirement: 'None',
    recommendedStage: 'foundation',
    status: 'active',
    featured: false,
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
  },
];
