import { Bank } from '@/types/bank';

export const INITIAL_BANKS: Bank[] = [
  {
    id: 'bank-relay',
    name: 'Relay Financial',
    slug: 'relay-financial',
    description: 'Online business banking built for small businesses and growing teams. Open up to 20 individual checking accounts, issue up to 50 physical and virtual debit cards, and organize cash flow with automated savings rules.',
    shortDescription: 'Modern online business checking with multi-account cash flow management and no monthly fees.',
    logoUrl: '/logos/relay.svg',
    websiteUrl: 'https://relayfi.com',
    affiliateUrl: 'https://relayfi.com/?via=crediqly',
    affiliateEnabled: true,
    featured: true,
    status: 'active',
    priority: 1,
    displayOrder: 1,
    recommendedStage: 'foundation',
    minDeposit: '$0',
    monthlyFee: '$0',
    features: [
      'No account maintenance or overdraft fees',
      'Up to 20 checking accounts to separate tax & payroll',
      'Up to 50 virtual and physical debit cards',
      'Seamless QuickBooks Online & Xero integrations',
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'bank-bluevine',
    name: 'Bluevine Business Checking',
    slug: 'bluevine-business-checking',
    description: 'High-yield commercial business checking account designed for modern small businesses. Earn competitive APY interest on balances while enjoying unlimited transactions and zero monthly maintenance fees.',
    shortDescription: 'High-yield checking account offering competitive interest and zero monthly fees.',
    logoUrl: '/logos/bluevine.svg',
    websiteUrl: 'https://www.bluevine.com',
    affiliateUrl: 'https://www.bluevine.com/?ref=crediqly',
    affiliateEnabled: true,
    featured: true,
    status: 'active',
    priority: 1,
    displayOrder: 2,
    recommendedStage: 'foundation',
    minDeposit: '$0',
    monthlyFee: '$0',
    features: [
      'Earn up to 2.0% APY on eligible balances',
      'Unlimited monthly transactions',
      'Zero monthly maintenance fees',
      'FDIC insured up to $3,000,000 through sweep program',
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'bank-mercury',
    name: 'Mercury',
    slug: 'mercury',
    description: 'Commercial banking and financial stack crafted for tech startups, ecommerce, and scaling enterprises. Features robust API access, automated wire transfers, and yield on treasury balances.',
    shortDescription: 'Commercial banking and treasury management built for modern startups and scaling businesses.',
    logoUrl: '/logos/mercury.svg',
    websiteUrl: 'https://mercury.com',
    affiliateUrl: 'https://mercury.com/?partner=crediqly',
    affiliateEnabled: false,
    featured: false,
    status: 'active',
    priority: 2,
    displayOrder: 3,
    recommendedStage: 'building',
    minDeposit: '$0',
    monthlyFee: '$0',
    features: [
      'Free domestic and USD international wire transfers',
      'Virtual cards with custom spending limits',
      'Multi-user permission levels and approval flows',
      'Direct integrations with Stripe, PayPal, and Shopify',
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'bank-chase',
    name: 'Chase Business Complete Banking',
    slug: 'chase-business-complete-banking',
    description: 'Comprehensive branch and mobile business banking from JPMorgan Chase. Integrated QuickAccept card payment processing and nationwide access to branches and ATMs.',
    shortDescription: 'Full-service business banking with built-in card processing and nationwide branch access.',
    logoUrl: '/logos/chase.svg',
    websiteUrl: 'https://www.chase.com/business',
    affiliateUrl: 'https://www.chase.com/business?promo=crediqly',
    affiliateEnabled: false,
    featured: false,
    status: 'active',
    priority: 2,
    displayOrder: 4,
    recommendedStage: 'foundation',
    minDeposit: '$0',
    monthlyFee: '$15 (waived with $2,000 min daily balance)',
    features: [
      'Built-in Chase QuickAccept credit card processing',
      'Same-day deposits with QuickAccept at no extra cost',
      'Access to 4,700 branches and 15,000 ATMs',
      'Dedicated business relationship managers',
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];
